# Generated by Django 3.2.6 on 2021-08-10 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='downvotes',
            field=models.ManyToManyField(related_name='commentDownvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvotes',
            field=models.ManyToManyField(related_name='commentUpvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
