# Generated by Django 2.2.10 on 2021-07-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('director', models.CharField(max_length=128)),
                ('year', models.IntegerField(default=1895)),
                ('rating', models.IntegerField(default=0)),
                ('synopsys', models.CharField(max_length=2000)),
                ('actors', models.CharField(max_length=2000)),
            ],
        ),
    ]
