"""
Django settings for moviemon project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import random

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u56!gqlyjeurh2u-p$#)#kd@wp22$1c%b$8eaqec4o0@_%w=_2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'game'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'moviemon.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'static', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'moviemon.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static/static-only')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

DEFAULT_GAME_SIZE = 64

DEFAULT_AMOUNT_BALL = 0

DEFAULT_START_PLAYER_POSITION = [0, 0]

SAVED_DIR = "saved_game/"

SAVED_PATH = BASE_DIR + "/" + SAVED_DIR

LOAD_FLAG = 0

# defines

tmp_random = random.randrange(1, 4)

if tmp_random == 1:
	MOVIES = [
		"Joker",
		"La La Land",
		"Gisaengchung",
		"Forrest Gump",
		"Penguins of Madagascar",
		"Mr. Popper's Penguins",
		"The Amazing Spider-Man",
		"Escape Room: Tournament of Champions",
		"Manos: the Hands of Fate",
		"Disaster Movie",
		"The Emoji Movie",
		"Captain America"
	]

elif tmp_random == 2:
	MOVIES = [
		"I Am Sam",
		"Harry Potter and the Sorcerer's Stone",
		"Cruella",
		"the Dark Knight",
		"Twilight",
		"Chernobyl",
		"the Boss Baby: Family Business",
		"Suicide Squad",
		"D-War",
		"Hercules in New York"
		"Far Cry",
		"Vampires Suck"
	]

elif tmp_random == 3:
	MOVIES = [
		"John Wick: Chapter 3 - Parabellum",
		"Django",
		"Kung fu",
		"Godfather",
		"Venom",
		"The Hitman's Bodyguard",
		"Lo chiamavano Trinità...",
		"Night at the Museum",
		"Kod Adi K.O.Z.",
		"Saving Christmas"
		"House of the Dead",
		"The Hottie & the Nottie"
	]

API_KEY="85b022eb"
SIZE_MOVIE = len(MOVIES)

MOVIES_IMDB = {}

INDEX = 0
TOKEN =''
BALLS = 150