version: '3.7'
services:
    app:
        build:
            context: .
        command: >
                sh -c "python manage.py makemigrations &&
                       python manage.py migrate &&
                       gunicorn --workers=3 --timeout=0 Rush01.wsgi:application --bind=0.0.0.0:8000"
        volumes:
            - ./static:/usr/src/app/static
            - ./media:/usr/src/app/media
            - ./:/usr/src/app
        ports:
            - "8000:8000"
        expose:
            - "8000"
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./static:/usr/src/app/static
            - ./media:/usr/src/app/media
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
